name: MCPluginV2
main: fr.triedge.minecraft.plugin.v2.MCPlugin
version: 1.16
author: Jikai
api-version: 1.16

commands:
  warp:
    description: Manipule les teleporteurs
    usage: /warp [ create | remove | setgroup ] TP_NAME [GROUP_NAME]
  warpgroup:
    description: Manipule les groupes
    usage: /warp [ create | remove ] TP_NAME