name: MCPluginV2
main: fr.triedge.minecraft.plugin.v2.MCPluginV2
version: 1.16
author: Jikai
api-version: 1.16

commands:
  warp:
    description: Manipule les teleporteurs
    usage: /warp create|remove|setgroup|removegroup TP_NAME [GROUP_NAME]
  warpgroup:
    description: Manipule les groupes
    usage: /warpgroup create|delete|add|remove TP_NAME [PLAYER_NAME]
  detector:
    description: Detecte les metaux
    usage: /detector